Cyber.Application/Cyber.Application/Controllers/RepositoryController.cs
using OfficeApplication.BLL.Helpers;
using OfficeApplication.BLL.Modals;
using OfficeApplication.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OfficeApplication.Controllers
{
    [SessionExpire]
    public class RepositoryController : Controller
    {
        // GET: Repository
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetAllRepositories()
        {
            List<RepositoryModal> FolderList = new List<RepositoryModal>();
            try
            {
                APIHelper _helper = new APIHelper();
                FolderList = _helper.GetAllRepositories();
                if (FolderList != null && FolderList.Count > 0)
                {
                    FolderList = FolderList.OrderBy(x => x.Name).ToList();
                }
                //string path = @"C:\ProgramData\Carisbrooke Shipping Ltd\ISM Dashboard\Repository";
                //ListDirectories(path, Guid.Empty.ToString(), ref FolderList);
            }
            catch (Exception ex)
            {
                LogHelper.writelog(ex.Message);
            }
            return Json(FolderList, JsonRequestBehavior.AllowGet);
        }
        void ListDirectories(string path, string parentid, ref List<DocumentFolders> FolderList)
        {
            var directories = Directory.GetDirectories(path);
            if (directories.Any())
            {
                foreach (var directory in directories)
                {
                    string docID = Guid.NewGuid().ToString();
                    var di = new DirectoryInfo(directory);
                    FolderList.Add(new DocumentFolders { DocumentID = docID, ParentID = parentid, Name = di.Name, Type = "FOLDER", Extension = string.Empty, Version = 1.0, Path = directory });
                    foreach (string file in Directory.GetFiles(directory))
                    {
                        string docFileID = Guid.NewGuid().ToString();
                        FolderList.Add(new DocumentFolders { DocumentID = docFileID, ParentID = docID, Name = Path.GetFileName(file), Type = "File", Extension = Path.GetExtension(file).ToUpper(), Version = 1.0, Path = file });
                    }
                    ListDirectories(directory, docID, ref FolderList);
                }
            }
        }
        [HttpPost]
        public ActionResult AddNewFile(List<HttpPostedFileBase> postedFiles, FormCollection coll)
        {
            try
            {
                foreach (HttpPostedFileBase postedFile in postedFiles)
                {
                    if (postedFile != null && postedFile.ContentLength > 0)
                    {
                        string _FileName = Path.GetFileName(postedFile.FileName);
                        string Repositorypath = coll["hdnDocPath"];
                        string path = Path.Combine(@"C:\ProgramData\Carisbrooke Shipping Ltd\ISM Dashboard\", Repositorypath);
                        postedFile.SaveAs(path + _FileName);
                    }
                }
                ViewBag.Message = "File Added Successfully!!";
                return View();
            }
            catch
            {
                ViewBag.Message = "File adding failed!!";
                return View();
            }
        }
    }

}

Cyber.Application/Cyber.Application/Views/Repository/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<style type="text/css">
    .doc-title:hover {
        cursor: pointer;
        color: black;
    }

    .box {
        margin-bottom: 1px !important;
    }

    .DocHeader {
        margin: 0px;
        font-size: 18px;
    }

        .DocHeader a {
            color: #444;
        }

            .DocHeader a:hover {
                background: none !important;
            }

    .box-header:hover {
        background-color: #3333;
    }

    .doc-title-a {
        font-size: 20px;
    }
</style>

<script src="~/Scripts/jquery/jquery.min.js"></script>
<section class="content">
    <div class="row">
        <div class="col-md-12 lblHeaderText">
            <h4 id="lblISM">
                Select Folder
            </h4>
        </div>
    </div>
    <div class="row uploadDocDiv" style="display:none;margin-top:10px;">
        <div class="col-md-12">
            @using (Html.BeginForm("", "", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="row">
                    <input type="hidden" id="hdnDocPath" name="hdnDocPath" value="" />
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="txtFolderName" />
                            </div>
                            <div class="col-md-4">
                                <button type="button" class="btn btn-primary">Create new folder</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="col-md-10">
                            <div class="input-group">
                                <label class="input-group-btn">
                                    <span class="btn btn-primary">
                                        Choose New Document&hellip; <input type="file" name="postedFiles" multiple="multiple" style="display: none;">
                                    </span>
                                </label>
                                <input type="text" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-primary" style="float:right;">Upload</button>
                        </div>
                    </div>
                </div>
                <br />
            }
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 newcontent">

        </div>
    </div>
</section>

<script type="text/javascript">
    var AllDirectories;
    var FolderPathArray = [];
    function GetAllDirectories() {
        $.ajax({
            type: "GET",
            url: '@Url.Action("GetAllRepositories", "Repository")',
            async: false,
            success: function (res) {
                if (res != null && res.length > 0) {
                    AllDirectories = res;
                    $(".newcontent").html("");
                    var html = '';
                    html += '<div class="box box-solid collapsed-box">';
                    html += '<div class="box-header with-border"><i class="fa fa-folder-o"></i> <h3 data-DocumentID=00000000-0000-0000-0000-000000000000' +
                               ' data-ParentID=00000000-0000-0000-0000-000000000000' +
                               ' class="box-title doc-title" data-widget="collapse">Repository' +
                               '</h3></div>';
                    html += '</div>';
                    $(".newcontent").append(html);
                    $('.doc-title').click(function (e) {
                        try {
                            var DocumentID = $(this).attr("data-DocumentID");
                            FolderPathArray.push({ "Name": "Repository", "DocumentID": "00000000-0000-0000-0000-000000000000", "ParentID": "00000000-0000-0000-0000-000000000000" })
                            CreateFolderPathLink();
                            $(".uploadDocDiv").show();
                            GetSubDirectories(DocumentID);
                        }
                        catch (e) { }
                    });
                    $('.doc-title-a').click(function (e) {
                        try {
                            var DocumentID = $(this).attr("data-DocumentID");
                            GetSubDirectories(DocumentID);
                        }
                        catch (e) { }
                    });
                }
            },
            error: function () {
            }
        });
    }

    function GetIcon(Type) {
        var iconfile = "<i class='fa fa-folder-o'></i>";
        if (Type == "File")
            iconfile = "<i class='fa fa-file-text-o'></i>"
        return iconfile;
    }

    function CreateDirs(MainDirectories) {
        $(".newcontent").html("");
        var html = '';
        for (x in MainDirectories) {
            var iconfile = GetIcon(MainDirectories[x].Type);
            html += '<div class="box box-solid collapsed-box">';
            html += '<div class="box-header with-border">' + iconfile + '<h3 data-DocumentID=' + MainDirectories[x].DocumentID +
                       ' data-ParentID=' + MainDirectories[x].ParentID +
                       ' class="box-title doc-title" data-widget="collapse">' + MainDirectories[x].Name +
                       '</h3></div>';
            html += '</div>';
        }
        $(".newcontent").append(html);
        $('.doc-title').click(function (e) {
            try {
                var Name = $(this).text();
                var DocumentID = $(this).attr("data-DocumentID");
                var ParentID = $(this).attr("data-ParentID");
                SetHeaderLabel(Name, DocumentID, ParentID);
                GetSubDirectories(DocumentID);
            }
            catch (e) { }
        });
    }

    function GetSubDirectories(DocumentID) {
        var Categories = AllDirectories.filter(function (x) {
            return x.ParentID == DocumentID;
        })
        CreateDirs(Categories);
    }

    function SetHeaderLabel(Name, DocumentID, ParentID) {
        FolderPathArray.push({ "Name": Name, "DocumentID": DocumentID, "ParentID": ParentID })
        CreateFolderPathLink();
    }

    function CreateFolderPathLink() {
        var html = "";
        for (x in FolderPathArray) {
            if (x == 0) {
                html = "<a data-DocumentID='" + FolderPathArray[x].DocumentID + "' data-ParentID='" + FolderPathArray[x].ParentID + "' class='doc-title-a' href=#>" + FolderPathArray[x].Name + "</a>";
            }
            else {
                html = html + " > " + "<a data-DocumentID='" + FolderPathArray[x].DocumentID + "' data-ParentID='" + FolderPathArray[x].ParentID + "' class='doc-title-a' href=#>" + FolderPathArray[x].Name + "</a>";
            }
        }

        $(".lblHeaderText").html("");
        $(".lblHeaderText").html(html);

        $('.doc-title-a').click(function (e) {
            try {
                var Name = $(this).text();
                var DocumentID = $(this).attr("data-DocumentID");
                removeItemsByName(FolderPathArray, Name);
                GetSubDirectories(DocumentID);
                CreateFolderPathLink();
            }
            catch (e) { }
        });
        CreateRepositoryPath();
    }

    function removeItemsByName(arr, Name) {
        var index;
        for (x in FolderPathArray) {
            if (FolderPathArray[x].Name == Name) {
                index = parseInt(x);
            }
        }
        FolderPathArray.splice(index + 1, FolderPathArray.length - 1);
    }

    function CreateRepositoryPath() {
        var path;
        for (x in FolderPathArray) {
            if (x == 0) {
                path = FolderPathArray[x].Name + "\\";
            }
            else {
                path = path + FolderPathArray[x].Name + "\\";
            }
        }
        $("#hdnDocPath").val(path);
    }

    $(document).ready(function () {
        GetAllDirectories();
        var height = $(".content-wrapper").height();
        $(".newcontent").height(height - 150);
    });
</script>