Cyber.Application/Cyber.Application/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OfficeApplication.BLL.Modals;
using OfficeApplication.BLL.Helpers;
using OfficeApplication.Models;
using System.IO;
using Newtonsoft.Json;
using static OfficeApplication.BLL.Modals.AppStatic;
using System.Xml;

namespace OfficeApplication.Controllers
{
    [SessionExpire]
    public class FormsController : Controller
    {
        #region Forms
        // GET: Forms
        public ActionResult Index()
        {
            try
            {
                List<FormModal> FormList = new List<FormModal>();

                // Get Data Via API
                APIHelper _aHelper = new APIHelper();
                FormList = _aHelper.GetAllForms();

                if (FormList != null && FormList.Count > 0)
                {
                    //string path;
                    foreach (var item in FormList)
                    {
                        try
                        {
                            //if (item.Code == "RWHS")
                            //{
                            //    item.TemplatePath = JsonConvert.SerializeObject(item.TemplatePath);
                            //}
                            //else
                            //{
                            //path = item.TemplatePath.Replace(@"C:\ProgramData\Carisbrooke Shipping Ltd\ISM Dashboard\", "");
                            //path = Server.MapPath(path);
                            item.TemplatePath = JsonConvert.SerializeObject(item.TemplatePath);
                            //}
                        }
                        catch (Exception ex)
                        {
                            LogHelper.writelog("Forms->Index " + ex.Message);
                        }
                    }
                    //FormList.ForEach(x => x.TemplatePath = JsonConvert.SerializeObject(x.TemplatePath));

                    FormList = FormList.Where(x => x.CanBeOpened.HasValue && x.CanBeOpened.Value).OrderBy(x => x.Title).ToList();
                }
                ViewBag.FormList = FormList;
                //try
                //{
                //    LogHelper.writelog("Forms->Index Start right"  + Server.MapPath("~/Repository/DocumentsIndex.xml"));
                //    RiskAssessmentFormHelper _helper = new RiskAssessmentFormHelper();
                //    _helper.InsertDocumentsInRiskAssessmentData(Server.MapPath("~/Repository/DocumentsIndex.xml"), SessionManager.ShipCode, SessionManager.ShipName, SessionManager.Username);
                //}
                //catch (Exception e)
                //{
                //    LogHelper.writelog("Forms->Index : Error creating an entries" + e.Message);
                //}
            }
            catch (Exception ex)
            {
                LogHelper.writelog("Forms->Index " + ex.Message);
            }
            return View();
        }
        public JsonResult GetAllForms()
        {
            APIHelper _helper = new APIHelper();
            List<FormModal> DocList = _helper.GetAllForms();
            if (DocList != null && DocList.Count > 0)
            {
                DocList = DocList.OrderBy(x => x.Category).ToList();
            }
            return Json(DocList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CreatePDF(string path)
        {
            // DocumentTableHelper _helper = new DocumentTableHelper();
            // string path = string.Empty;
            string mimeType = string.Empty;
            mimeType = MimeMapping.GetMimeMapping(Path.GetFileName(path));
            try
            {
                if (mimeType != "PDF")
                {
                    string filename = Path.GetFileName(path);
                    byte[] fileBytes = System.IO.File.ReadAllBytes(path);
                    return File(fileBytes, "application/force-download", filename);
                }
            }
            catch (Exception ex)
            {
                LogHelper.writelog(ex.Message);
            }
            if (!string.IsNullOrWhiteSpace(path))
                return File(path, mimeType);
            TempData["ErrorMsg"] = "Document is not exist.";
            TempData.Keep();
            return RedirectToAction("Index", "Documents");
        }
        #endregion

        #region SRM
        public ActionResult SMR()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SMR(SMRFormReq Modal)
        {
            APIHelper _helper = new APIHelper();
            List<SMRModal> ModalList = _helper.GetSMRFormsFilled(Modal);
            ViewBag.Searched = Modal;
            return View(ModalList);
        }
        public ActionResult SMRDetails(string id)
        {
            SMRModal Modal = new SMRModal();
            long SMRID = Utility.ToLong(id);
            if (SMRID > 0)
            {
                APIHelper _helper = new APIHelper();
                Modal = _helper.GetSMRFormByID(SMRID);
            }
            else
            {
                Modal = null;
            }
            return View(Modal);
        }
        #endregion

        #region GIR
        public ActionResult GeneralInspectionReport()
        {
            APIHelper _helper = new APIHelper();
            List<GIRData> ModalList = _helper.GetGIRFormByID();
            return View(ModalList);
        }
        [HttpPost]
        public ActionResult GeneralInspectionReportList()
        {
            APIHelper _helper = new APIHelper();
            List<GIRData> ModalList = _helper.GetGIRFormByID();
            return Json(ModalList, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GIRDetails(string code)
        {
            List<GIRDataList> Modal = new List<GIRDataList>();
            if (code != "")
            {
                APIHelper _helper = new APIHelper();
                Modal = _helper.GetDeficienciesData(code);
            }
            else
            {
                Modal = null;
            }
            return Json(Modal, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult UpdateDeficienciesData(string id, string isClose)
        {
            bool res = false;
            if (id != "")
            {
                APIHelper _helper = new APIHelper();
                res = _helper.UpdateDeficienciesData(Convert.ToInt32(id), Convert.ToBoolean(isClose));
            }
            return Json(res, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult AddDeficienciesNote(DeficienciesNote notes)
        {
            long res = 0;
            if (notes != null)
            {
                APIHelper _helper = new APIHelper();
                _helper.AddDeficienciesNote(notes);
            }
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetDeficienciesNote(int id)
        {
            List<DeficienciesNote> response = new List<DeficienciesNote>();
            if (id != 0)
            {
                APIHelper _helper = new APIHelper();
                response = _helper.GetDeficienciesNote(id);
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetDeficienciesFiles(int id)
        {
            List<GIRDeficienciesFile> response = new List<GIRDeficienciesFile>();
            if (id != 0)
            {
                APIHelper _helper = new APIHelper();
                response = _helper.GetDeficienciesFiles(id);
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Download(int file, string name)
        {
            APIHelper _helper = new APIHelper();
            string GetFile = _helper.GetFile(file);
            string filepath = System.Configuration.ConfigurationManager.AppSettings["FilePath"].ToString() + "/" + GetFile;
            LogHelper.writelog("---------" + filepath + "----------");
            byte[] fileBytes = System.IO.File.ReadAllBytes(filepath);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, name);
        }
        public ActionResult DownloadCommentFile(int file, string name)
        {
            APIHelper _helper = new APIHelper();
            string GetFile = _helper.GetFileComment(file);
            string filepath = System.Configuration.ConfigurationManager.AppSettings["FilePath"].ToString() + "/" + GetFile;
            LogHelper.writelog("---------" + filepath + "----------");
            byte[] fileBytes = System.IO.File.ReadAllBytes(filepath);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, name);
        }
        #endregion

        #region Risk Assessment Form
        public ActionResult RiskAssessmentFormList()
        {
            return View();
        }

        public ActionResult GetRiskAssessmentFormList(string ship)
        {
            APIHelper _helper = new APIHelper();
            List<RiskAssessmentForm> Modal = new List<RiskAssessmentForm>();
            Modal = _helper.GetRiskassessmentForm(ship);

            return Json(Modal, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RAformData(int? id = 0, string shipCode = "", string docid = "")
        {
            RiskAssessmentFormModal Modal = new RiskAssessmentFormModal();
            ViewBag.result = Utility.ToString(TempData["RAFRes"]);
            ViewBag.CurrentDateString = Utility.GetCurrentDateShortString();
            APIHelper _helper = new APIHelper();
            try
            {
                if (string.IsNullOrWhiteSpace(shipCode))
                    shipCode = SessionManager.ShipCode;


                if (id > 0)
                {
                    Modal = _helper.RAFormDetailsView(shipCode, Convert.ToInt32(id));

Cyber.Application/Cyber.Application/Controllers/SIRListController.cs
using OfficeApplication.BLL.Helpers;
using OfficeApplication.BLL.Modals;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace OfficeApplication.Controllers
{
    public class SIRListController : Controller
    {
        // GET: SIRList
        public ActionResult Index()
        {
            APIHelper _helper = new APIHelper();
            List<SuperintendedInspectionReport> list = new List<SuperintendedInspectionReport>();
            list = _helper.GetAllSIRForms();
            ViewBag.Listdata = list.OrderByDescending(x => x.Date);
            return View();
        }
        [HttpGet]
        public ActionResult DetailsView(int id, bool isDefectSection = false,string no="")
        {
            APIHelper _helper = new APIHelper();
            SIRModal list = new SIRModal();
            list = _helper.SIRFormDetailsView(id);
            if(no!="")
                ViewBag.No = "section"+no.Split('.')[0];
            return View(list);
        }
    }
}

Cyber.Application/Cyber.Application/Views/SIRList/Index.cshtml
@model IEnumerable<OfficeApplication.BLL.Modals.SIRModal>

@{
    ViewBag.Title = "Index";
}


<script>
    var RootUrl = '@Url.Content("~/")';
    function ViewGIRForm(ctr) {
        var url = RootUrl + 'GIRList/Index?id=' + ctr;
        alert(ctr)
        $.ajax({
            type: 'GET',
            dataType: 'json',
            async: false,
            url: url,

            success: function (Data) {

            },
            error: function (data) {
                console.log(data);
            }
        });
    }
    function LoadGrid() {
        var month = $("#ddlReportPeriod").val();

        var array = @Html.Raw(Json.Encode(@ViewBag.Listdata));
        var obj = new Array();
        for (var i = 0; i < array.length; i++) {
            var item = new Object();
            item.ShipName = array[i].ShipName;
            item.SIRFormID = array[i].SIRFormID;
            item.Date = array[i].Date;
            item.Port = array[i].Port;
            item.Inspector = array[i].Inspector;
            obj.push(item);
        }
        $('#grid').empty();
        $('#grid').kendoGrid({

                    scrollable: true,

                    filterable: true,
                    selectable: true,
                    change: function () {
                        var row = this.select();
                        var id = row[0].cells[1].textContent;
                        var _url = RootUrl + "SIRList/DetailsView?id=" + id ;
                        window.open(_url, '_blank');
                    },
                    pageable: {
                        alwaysVisible: true,
                        pageSizes: [5, 10, 20, 100]
                    },
                    dataSource: {
                        data: obj,
                        pageSize: 10
                    },
                    dataBound: function () {
                        for (var i = 0; i < this.columns.length; i++) {
                            this.autoFitColumn(i);
                        }
                    },
                    columns: [
                        {
                            field: "ShipName",
                            title: "Ship Name"
                        },
                        {
                            field: "SIRFormID",
                            title: "SIRFormID",
                            hidden: true
                        },
                        {
                            field: "Date",
                            title: "Date",
                            template: "#= Date!=null? kendo.toString(kendo.parseDate(Date, 'yyyy-MM-dd'), 'MM/dd/yyyy'):'' #"
                        },
                        {
                            field: "Port",
                            title: "Port"
                        },
                        {
                            field: "Inspector",
                            title: "Inspector"
                        }
                    ],

                    dataBound: function () {
                        var grid = this;
                        $(".k-grouping-row").each(function (e) {
                            grid.collapseGroup(this);
                        });
                    },

                });

    }

    $(document).ready(function () {
        LoadGrid();
    });
</script>
<div class="well well-sm" style="margin-bottom:0px;">General Inspection Reports <a href="@Url.Action("Index", "Forms")" class="label label-info" style="float:right;">GO BACK</a></div>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">

                    <input type="hidden" id="hdnSelectedVal" name="hdnSelectedVal" value="" />
                    <select name="ddlReportPeriod" id="ddlReportPeriod">
                        <option value="Annual">Annual</option>
                        <option value="January">January</option>
                        <option value="February">February</option>
                        <option value="March">March</option>
                        <option value="April">April</option>
                        <option value="May">May</option>
                        <option value="June">June</option>
                        <option value="July">July</option>
                        <option value="August">August</option>
                        <option value="September">September</option>
                        <option value="October">October</option>
                        <option value="November">November</option>
                        <option value="December">December</option>
                    </select>

                </div>
                <div class="box-body" id="ReportPage">
                    <div class="row">
                        <div class="col-md-12">
                            <div id="grid">
                                <div class="well">Loading Please Wait...</div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer clearfix no-border">
                        <button type="button" class="btn btn-default" onclick="PrintReport()"><i class="fa fa-print"></i> Print</button>&nbsp;&nbsp;&nbsp;
                        <a href="@Url.Action("DownloadInvoice", "Reports")" class="btn btn-default"><i class="fa fa-file-excel-o"></i> Export</a>
                    </div>

                </div>

            </div>
        </div>
    </div>
</section>